### ISSUE TITLE
Pruner Configuration Update

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#1727]
The TTL format doesn't make sense in the config for its purpose. Since we have expanded the scope and implementation of the pruner, the config values are placed in TTL but it doesn't truly fit there. 

Admin and Orpan pruner are cleanup functions and shouldn't be something the system admin needs to configure. Potentially, we could add a flag to disable cleanup.

config.yaml proposed changes

```yaml
# ORIGINAL
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden
  prune_interval: 15
  ttl:
    action: -1
    file: 15
    in_progress: 15
    info: 15   
    temp: 15
    admin: 15
    
    orphan: -1

    batch_size: -1

# CHANGES
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden
  prune:    
    batch_size: 1000
    execution_interval: 15
    in_progress_request_expiration: 180
    type:
      action: -1
      file: 15
      info: 15   
```
