### ISSUE TITLE
3.15 to 3.29 Topics Table Failure

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#1736]
Something happens when upgrading from 3.15 to 3.29 to the Topics table where things are added to the table, but nothing is returned from `get_topics`. Required a drop of the topics collection to manually fix this. Need to investigate why this was happening.

**Comment by TheBurchLog** [comment]
Attempted to reproduce with the following version in Docker Compose. It successfully created and returned the topics when called from the topics plugin.

```yaml
services:
    beer-garden:
        # image: bgio/beer-garden:3.15.0
        image: bgio/beer-garden:3.29.0-python3.9
```
