### ISSUE TITLE
Child BG Registration

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#362]
At start-up, BG instance should register with parent in a similar process to Remote Plug-ins / Systems.

Example Config:
```
parent:
    http:
        enable: false
        host: 0.0.0.0
        port: 2337
        public_fqdn: remotehost
        ssl:
          ca_cert: null
          ca_path: null
          client_cert_verify: NONE
          enabled: false
          private_key: null
          public_key: null
        url_prefix: /
        remote_username: bg_remote
        username: username
        password: password
```
